### PR TITLE
TypeScript and documentation fixes

### LINKED ISSUE #73: Typescript definitions are incorrect for gstime function
The TypeScript definition for `gstime` is defined as `export function gstime(date: Date): GMSTime;`

This is not correct, since `gstime` can take a `Date`, Julian date (`number`), or any valid params for `jday()`

### LINKED ISSUE #74: Documentation or implementation error for `degreesLat` and `degreesLong`
In the README, there is a section that says:
```
//  Convert the RADIANS to DEGREES for pretty printing (appends "N", "S", "E", "W", etc).
var longitudeStr = satellite.degreesLong(longitude),
    latitudeStr  = satellite.degreesLat(latitude);
```

The code for `degreesLong` and `degreesLat`, however, only returns numerical values without any of "N", "S", "E", or "W" appended. I'm not sure if this is a documentation error or an implementation error.

If it's a documentation error, the TypeScript definitions should be changed so that `degreesLat` and `degreesLong` return `number` instead of `string`.

### PR DESCRIPTION
**Pull request by iamthechad**
Fixes #73, Fixes #74

### CODE REVIEW

**Comment by ezze** [comment]
@iamthechad Thanks for this!!!

File: types/index.d.ts [hunk 1]
```diff
@@ -144,10 +144,24 @@ declare module 'satellite.js' {
...
+   * @param dateYearArg Can be a Date, Julian date, or the year number for
+   * @param month Zero-based month number
+   * @param day Day of month
+   * @param hour Hour of day, based on 24 hour clock
+   * @param minute Minute(s)
+   * @param second Second(s)
+   * @param msec Optional milliseconds
+   */
+  export function gstime(
+      dateYearArg: number | Date,
```
Comment (kylegmaxwell) [inline types/index.d.ts:158]: Thanks for fixing this!
